### ISSUE TITLE
hur kunde det bli en fork?

### ISSUE THREAD

**Issue by Mehetweret** [Mehetweret/Laboration#1]
av att titta på någons projekt?
Tittade här:
https://github.com/oreillymedia/open_government
och vips var den forkad till mitt konto:
https://github.com/Mehetweret/open_government/commits/master

Och hur tar man bort det?

**Comment by Mehetweret** [comment]
man klickar på fork på nåns projekt så får man nån slags kopia till sitt konto. oklart hur man blir av med det.

**Comment by Mehetweret** [comment]
och sen deleatar man under inställningar i sin kopia! trots varningar!

**Comment by Barbapappa** [comment]
https://help.github.com/articles/deleting-a-repository/

**Comment by Barbapappa** [comment]
Varningarna är märkligt allvarliga, ja ... För att inte säga missvisande.
